# Generated by Django 5.2.6 on 2025-09-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='references/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
