# Generated by Django 5.2.3 on 2025-09-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='file',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(default='', upload_to='certificates/'),
            preserve_default=False,
        ),
    ]
