# Generated by Django 5.2.6 on 2025-09-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_remove_certificate_file_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
