# Generated by Django 5.2.6 on 2025-09-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_certificate_file_alter_certificate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='photo',
            new_name='main_photo',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(default='', upload_to='certificates/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='references/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reference.reference')),
            ],
        ),
    ]
