# Generated by Django 5.2.6 on 2025-09-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_rename_photo_reference_main_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='main_photo',
            new_name='photo',
        ),
    ]
