# Generated by Django 5.2.6 on 2025-09-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_alter_service_description_serviceimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
