# Generated by Django 5.2.6 on 2025-09-14 17:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0012_delete_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimage',
            old_name='caption',
            new_name='alt_text',
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='service_gallery/'),
        ),
    ]
